Refactor Jenkinsfile for improved structure and commands

diff --git a/ml-inference-api/Jenkinsfile b/ml-inference-api/Jenkinsfile
--- a/ml-inference-api/Jenkinsfile
+++ b/ml-inference-api/Jenkinsfile
@@ -9,36 +9,39 @@ pipeline {
 
         stage('Clone Repository') {
             steps {
-                git branch: 'main',
-                credentialsId: 'git',
-                url: 'https://github.com/Karthikbale/ml-inference-api.git'
+                git 'https://github.com/Karthikbale/ml-inference-api.git'
             }
         }
 
         stage('SonarQube Analysis') {
             steps {
-                withSonarQubeEnv('Sonar') {
-                    sh '''
-                    sonar-scanner \
-                    -Dsonar.projectKey=ml-project \
-                    -Dsonar.sources=. \
-                    -Dsonar.host.url=http://sonarqube:9000 \
-                    -Dsonar.login=$SONAR_AUTH_TOKEN
-                    '''
+                dir('ml-inference-api') {
+                    withSonarQubeEnv('Sonar') {
+                        sh '''
+                        sonar-scanner \
+                        -Dsonar.projectKey=ml-project \
+                        -Dsonar.sources=. \
+                        -Dsonar.host.url=http://sonarqube:9000 \
+                        -Dsonar.login=$SONAR_TOKEN
+                        '''
+                    }
                 }
             }
         }
 
         stage('Build Docker Image') {
             steps {
-                sh "docker build -t ${IMAGE_NAME} ."
+                dir('ml-inference-api') {
+                    sh 'docker build -t ml-inference-api .'
+                }
             }
         }
 
         stage('Deploy Container') {
             steps {
                 sh '''
-                docker rm -f ml-container || true
+                docker stop ml-container || true
+                docker rm ml-container || true
                 docker run -d -p 8000:8000 --name ml-container ml-inference-api
                 '''
             }
@@ -47,10 +50,10 @@ pipeline {
 
     post {
         success {
-            echo "Pipeline executed successfully 🚀"
+            echo 'Pipeline successful 🚀'
         }
         failure {
-            echo "Pipeline failed ❌"
+            echo 'Pipeline failed ❌'
         }
     }
 }
